apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kilo
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kilo
        args:
        - --cni=false
        - --compatibility=flannel
        - --local=false
